name: project
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly
    - matplotlib
    - folium
    - fonttools
    - streamlit-folium
    - requests
    # - scikit-learn
    # - seaborn