name: project
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    - matplotlib==3.8.4
    - folium==0.16.0
    - fonttools==4.51.0
    - streamlit-folium==0.19.0
    # - scikit-learn
    # - seaborn